### ISSUE TITLE
Cannot find module 'electron'

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#15]
I'm trying to import InstallerDataService class into my tests, but it fails with the following error:
```Error: Cannot find module 'electron'```

I understand it can't get over this line in data.js:
```javascript
let ipcRenderer = require('electron').ipcRenderer;
```
Any idea how to get around this?

**Comment by kenfinnigan** [comment]
http://jbavari.github.io/blog/2015/08/12/writing-unit-tests-for-electron-and-angularjs/ and https://github.com/jprichardson/electron-mocha might provide some ideas.

Can also look at how Electron do tests: https://github.com/atom/electron/tree/master/spec

**Comment by kenfinnigan** [comment]
I think this is fixed now right @ppitonak ?

**Comment by ppitonak** [comment]
Yes, it's fixed now. However, we didn't use electron-mocha for now because I wanted to limit the number of dependencies. Before each run of tests, a new symlink is created (node_modules/electron -> node_modules/electron-prebuilt) and after test run it's removed. We will look into electron-mocha in the future.
